### ISSUE TITLE
mode tcp does not support quic listener?

### ISSUE THREAD

**Issue by mzealey** [haproxytech/quic-dev#1]
I'm using the latest `qns` branch and running in docker based on https://github.com/haproxytech/haproxy-qns/blob/master/Dockerfile

I'm wanting see if we can use haproxy to terminate quic traffic and map internally to tcp traffic (without ssl) - kind of like using haproxy for tls termination.

```
defaults
  mode tcp

frontend quic
    bind quic4@*:1234 proto quic ssl allow-0rtt crt ../fullchain.pem alpn our_proto
    default_backend backend
```

If I set `mode http` this build of haproxy-qns at least starts up, but it looks like using `mode tcp` it does not. Is the initial quic implementation only for http3-type connections, or is there some way to try enabling it as a termination for other protocols?

**Comment by a-denoyelle** [comment]
Sorry I did not see your issue before. First, note that this is not the main haproxy repository. This one is only used for development. You should use instead the following one, both for the code and for issue reporting : 
https://github.com/haproxy/haproxy

To answer to your question, currently quic is only able to be use with HTTP in haproxy. Therefore, it's impossible to use a tcp backend with it.

**Comment by Ra2-IFV** [comment]
> currently quic is only able to be use with HTTP in haproxy. Therefore, it's impossible to use a tcp backend with it.

Why? I'm interedted in how haproxy works and being programmed.

**Comment by Ra2-IFV** [comment]
*I remember you said haproxy won't be a QUIC load balancer, just wondering why
